### ISSUE TITLE
Minimum Viable Product Checklist

### ISSUE THREAD

**Issue by siefkenj** [uoft-tapp/tapp#346]
This issue is to track what is needed to get to a minimum viable product, which is a system that can deliver contracts to TAs and allows them to sign them.

- [x] working tests for all backend functions
- [x] implement logic to create an `offer`
- [x] set up the templates/pdf rendering to serve offers
- [x] interface to accept/reject offers
- [x] working emailing (and email templates) on backend
- [x] admin user interface polishing
- [x] Shibboleth/basic auth integration
- [x] Testing on deployment servers

**Comment by siefkenj** [comment]
Yes! We're deployed!
