### ISSUE TITLE
[frontend] Complete TODO Unit Tests

### ISSUE THREAD

**Issue by Altair59** [uoft-tapp/tapp#486]
- **user-permission-tests**
- [x] An instructor can access instructor routes
- [x] A TA can access TA routes
- [x] An instructor who is also a TA can access instructor and TA routes

- **template-tests**
- [x] upload a template

- **reporting-tag-tests**
- [ ] get all reporting_tags associated to positions for session
- [ ] get all reporting_tags associated to wage_chunks for session
- [ ] get reporting_tags for position
- [ ] get reporting_tags for wage_chunk
- [ ] create and delete reporting_tags for position
- [ ] create and delete reporting_tags for wage_chunk

- **import-export-tests**
- [x] Export data to a JSON/CSV/XLSX
- [x] Import data from a JSON/CSV/XLSX

- **ddah-tests**
- [x] getting ddahs for one session will not return ddahs for another session
